source("household-archetypes/src/single-mothers.R")
source("household-archetypes/src/fig05-table1-sample-composition-by-decade.R")
source("household-archetypes/src/fig01-single-mother-bedroom-dist-decade.R")
source("household-archetypes/src/fig02-single-mother-cost-burden-decade.R")
source("household-archetypes/src/fig03-single-mother-rent-burden-bedrooms-decade.R")
source("household-archetypes/src/fig04-single-mother-rent-burden-regressions.R")
